# Generated by Django 4.2.9 on 2024-03-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_user_is_oauth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_account_active",
            field=models.BooleanField(default=True),
        ),
    ]
