# Generated by Django 4.2.9 on 2024-03-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_user_is_account_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="nb_players",
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
