# Generated by Django 4.2.9 on 2024-03-24 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_tournament_nb_players"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
