# Generated by Django 4.2.9 on 2024-01-19 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hashed_password',
        ),
    ]
