# Generated by Django 4.2.9 on 2024-01-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_hashed_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pseudo',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
