# Generated by Django 4.2.9 on 2024-03-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_participants_list_tournament_invitations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, default="avatars/zippy.jpg", upload_to="avatars/"
            ),
        ),
    ]
