# Generated by Django 4.2.9 on 2024-03-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_oauth",
            field=models.BooleanField(default=False),
        ),
    ]
