# Generated by Django 4.2.9 on 2024-03-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_user_is_account_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_account_active",
        ),
    ]
