# Generated by Django 4.2.9 on 2024-03-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_game_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="status",
            field=models.CharField(default="waiting for player2", max_length=50),
        ),
    ]
