# Generated by Django 4.2.9 on 2024-03-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_game_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
